Fix broken import and broken import test (#122)
The import command threw the following error:

    Create file for import
    300+0 records in
    300+0 records out
    153600 bytes (154 kB, 150 KiB) copied, 0.000680805 s, 226 MB/s
    Import region
    Created new region file "/tmp/ds_test/export/region.json"
    Import file_size: 153600  Extent size: 51200  Needed extents: 3
    Region already large enough for image
    Importing "/tmp/ds_test/import" to region
    thread 'main' panicked at 'source slice length (51200) does not match destination slice length (0)'
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

This commit fixes the import so that it doesn't panic, fixes 
./tools/test_ds.sh so that the count is correct, and adds unit tests.